#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-validations
Version  : 1.2.0
Release  : 3
URL      : https://rubygems.org/downloads/dm-validations-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-validations-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-dm-types
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec

%description
This is a DataMapper plugin that provides validations for DataMapper model classes.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-validations-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-validations.gemspec

%build
gem build rubygem-dm-validations.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-validations-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/dm-validations-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/dm-validations.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/auto_validate.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/contextual_validators.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/formats/email.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/formats/url.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/support/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/support/ordered_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validation_errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/absent_field_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/acceptance_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/block_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/confirmation_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/format_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/generic_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/length_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/method_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/numeric_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/primitive_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/required_field_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/uniqueness_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/lib/dm-validations/validators/within_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/barcode.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/basketball_court.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/basketball_player.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/beta_tester_account.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/bill_of_landing.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/boat_dock.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/city.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/company.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/corporate_world.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/country.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/ethernet_frame.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/event.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/g3_concert.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/jabberwock.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/kayak.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/lernean_hydra.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/llama_spaceship.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/mathematical_function.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/memory_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/mittelschnauzer.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/motor_launch.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/multibyte.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/page.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/phone_number.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/pirogue.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/programming_language.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/reservation.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/scm_operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/sms_message.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/fixtures/udp_packet.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/absent_field_validator/absent_field_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/absent_field_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/acceptance_validator/acceptance_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/acceptance_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/custom_messages_for_inferred_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/disabling_inferred_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_boolean_properties_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_float_property_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_format_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_integer_properties_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_length_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_presence_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_primitive_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_uniqueness_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/inferred_within_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/automatic_validation/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/block_validator/block_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/block_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/conditional_validation/if_condition_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/conditional_validation/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/confirmation_validator/confirmation_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/confirmation_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/datamapper_models/association_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/datamapper_models/inheritance_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/dirty_attributes/dirty_attributes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/duplicated_validations/duplicated_validations_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/duplicated_validations/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/format_validator/email_format_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/format_validator/format_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/format_validator/regexp_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/format_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/format_validator/url_format_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/length_validator/default_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/length_validator/equality_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/length_validator/error_message_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/length_validator/maximum_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/length_validator/minimum_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/length_validator/range_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/length_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/method_validator/method_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/method_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/equality_with_float_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/equality_with_integer_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/float_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/gt_with_float_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/gte_with_float_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/integer_only_true_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/integer_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/lt_with_float_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/lte_with_float_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/numeric_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/primitive_validator/primitive_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/primitive_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/pure_ruby_objects/plain_old_ruby_object_validation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/association_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/boolean_type_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/date_type_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/datetime_type_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/float_type_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/integer_type_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/plain_old_ruby_object_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/shared_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/string_type_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/required_field_validator/text_type_value_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/shared/default_validation_context.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/shared/valid_and_invalid_model.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/uniqueness_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/uniqueness_validator/uniqueness_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/within_validator/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/integration/within_validator/within_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/public/resource_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/rcov.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/contextual_validators/emptiness_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/contextual_validators/execution_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/contextual_validators/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/generic_validator/equality_operator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/generic_validator/optional_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/validation_errors/adding_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/validation_errors/emptiness_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/validation_errors/enumerable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/validation_errors/reading_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/validation_errors/respond_to_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/spec/unit/validators/within_validator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-validations-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/dm-validations-1.2.0.gemspec
